"""Generate the Markdown pages derived from the data: STATUS.md, a README per domain, a page per
technology and the evidence index.

    python3 tools/generate.py           write the pages
    python3 tools/generate.py --check   exit 1 if a generated page is out of date

The pages are committed so they read well on GitHub. Never edit them by hand.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import atlas  # noqa: E402

HEADER = "<!-- Generated by tools/generate.py from {source}. Do not edit by hand. -->"
SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
STATUS_ORDER = ["tracked", "mapped", "scoping", "proposed", "achieved", "retired"]


def cell(text) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def node_id(tech_id: str) -> str:
    return tech_id.replace("/", "__").replace("-", "_")


def link(from_page: str, to_page: str, text: str) -> str:
    depth = from_page.count("/")
    return f"[{cell(text)}]({'../' * depth}{to_page})"


def people(from_page: str, handles: list, role: str) -> str:
    """GitHub handles as profile links, or how to volunteer for the role (GOVERNANCE.md)."""
    if not handles:
        return "none yet; see " + link(from_page, f"GOVERNANCE.md#{role}", "how to become one")
    return ", ".join(f"[@{name}](https://github.com/{name})" for name in handles)


def evidence_link(from_page: str, key: str) -> str:
    return link(from_page, f"evidence/{key}.toml", key)


class Context:
    def __init__(self):
        self.tax = atlas.taxonomy()
        self.techs = atlas.technologies()
        self.cards = atlas.evidence()
        self.required_by: dict[str, list[tuple[atlas.Technology, dict]]] = defaultdict(list)
        for tech in self.techs.values():
            for requirement in tech.requires():
                self.required_by[requirement.get("technology", "")].append((tech, requirement))
        self.cited_by: dict[str, set[str]] = defaultdict(set)
        for tech in self.techs.values():
            for key in self.cited_keys(tech):
                self.cited_by[key].add(tech.id)

    @staticmethod
    def cited_keys(tech: atlas.Technology) -> list[str]:
        keys = list(tech.data.get("readiness_evidence", []))
        for metric in tech.metrics():
            for part in ("current", "target", "limit"):
                key = metric.get(part, {}).get("evidence")
                if key:
                    keys.append(key)
            keys += [entry.get("evidence") for entry in metric.get("history", []) if entry.get("evidence")]
        for gap in tech.gaps():
            keys += gap.get("evidence", [])
            for approach in gap.get("approach", []):
                keys += approach.get("evidence", [])
        return list(dict.fromkeys(keys))

    def metric_def(self, metric: dict) -> dict:
        return self.tax.metrics.get(metric.get("metric", ""), {})

    def readiness(self, tech: atlas.Technology) -> str:
        return self.tax.level_name(self.tax.scale_of(tech), tech.data.get("readiness"))

    def headline_cells(self, tech: atlas.Technology, from_page: str) -> list[str]:
        metric = tech.headline()
        if metric is None:
            return ["–", "–", "–", "–"]
        definition = self.metric_def(metric)
        unit = definition.get("unit", "")
        current = metric.get("current", {}).get("value")
        target = metric.get("target", {}).get("value")
        size = atlas.gap_size(definition, current, target) if current is not None and target is not None else None
        return [
            cell(definition.get("name", metric.get("metric", ""))),
            atlas.format_value(current, unit),
            atlas.format_value(target, unit),
            atlas.format_gap(definition, size),
        ]

    def open_gaps(self, tech: atlas.Technology) -> list[dict]:
        return [gap for gap in tech.gaps() if gap.get("status") not in ("closed",)]


def mermaid(ctx: Context, tech_ids: list[str], edges: list[tuple[str, str]], focus: str | None = None) -> list[str]:
    lines = ["```mermaid", "graph LR"]
    for tech_id in tech_ids:
        tech = ctx.techs.get(tech_id)
        if tech is None:
            continue
        label = f"{tech.name}<br/><i>{tech.status}</i>"
        lines.append(f'  {node_id(tech_id)}["{label}"]')
    for source, target in edges:
        lines.append(f"  {node_id(source)} --> {node_id(target)}")
    lines += [
        "  classDef proposed fill:#f4f4f5,stroke:#a1a1aa,color:#3f3f46",
        "  classDef scoping fill:#fef9c3,stroke:#ca8a04,color:#713f12",
        "  classDef mapped fill:#dbeafe,stroke:#2563eb,color:#1e3a8a",
        "  classDef tracked fill:#dcfce7,stroke:#16a34a,color:#14532d",
        "  classDef achieved fill:#e0e7ff,stroke:#4f46e5,color:#312e81",
        "  classDef retired fill:#fafafa,stroke:#d4d4d8,color:#a1a1aa",
    ]
    for tech_id in tech_ids:
        tech = ctx.techs.get(tech_id)
        if tech is not None and tech.status:
            lines.append(f"  class {node_id(tech_id)} {tech.status}")
    if focus:
        lines.append(f"  style {node_id(focus)} stroke-width:3px")
    lines.append("```")
    return lines


def technology_page(ctx: Context, tech: atlas.Technology) -> str:
    page = tech.page
    data = tech.data
    domain = ctx.tax.domains.get(tech.domain, {})
    status = tech.status
    lines = [
        f"# {tech.name}",
        "",
        HEADER.format(source=f"atlas/{tech.domain}/{tech.slug}.toml"),
        "",
        f"> {cell(data.get('statement', ''))}",
        "",
        "| | |",
        "|---|---|",
        f"| Domain | [{cell(domain.get('name', tech.domain))}](README.md) |",
        f"| Atlas status | **{status}**: {cell(ctx.tax.vocabulary.get('technology_status', {}).get(status, ''))} |",
    ]
    readiness = ctx.readiness(tech)
    support = ", ".join(evidence_link(page, key) for key in data.get("readiness_evidence", []))
    lines.append(f"| Readiness | {readiness}{' (' + support + ')' if support else ''} |")
    if data.get("readiness_note"):
        lines.append(f"| Readiness note | {cell(data['readiness_note'])} |")
    if data.get("horizon"):
        lines.append(f"| Horizon | {data['horizon']} |")
    if data.get("sdgs"):
        sdgs = ", ".join(f"{number} {ctx.tax.sdgs.get(number, '')}" for number in data["sdgs"])
        lines.append(f"| Serves | UN SDG {cell(sdgs)} |")
    curators = data.get("curators", [])
    lines.append(
        f"| Curators | {people(page, curators, 'curators')} |"
    )
    lines.append(f"| Last reviewed | {data.get('last_reviewed', 'never')} |")
    book = data.get("alan_machine", [])
    if book:
        links = ", ".join(f"[{cell(item['title'])}]({atlas.ALAN_MACHINE_URL}{item['page']}/index.html)" for item in book)
        lines.append(f"| In The Alan Machine | {links} |")
    lines.append("")

    if data.get("scope"):
        lines += ["## Scope", "", " ".join(data["scope"].split()), ""]

    metrics = tech.metrics()
    if metrics:
        lines += [
            "## Metrics",
            "",
            "| Metric | Current | Target | Physical limit | Gap to target | Target to limit |",
            "|---|---|---|---|---|---|",
        ]
        notes = []
        for metric in metrics:
            definition = ctx.metric_def(metric)
            unit = definition.get("unit", "")
            name = cell(definition.get("name", metric.get("metric", "")))
            if metric.get("headline"):
                name = f"**{name}** (headline)"
            current = metric.get("current", {})
            target = metric.get("target", {})
            limit = metric.get("limit", {})
            current_text = atlas.format_value(current.get("value"), unit)
            if current.get("value") is not None:
                source = evidence_link(page, current["evidence"]) if current.get("evidence") else "no source"
                current_text += f" ({current.get('as_of', '')}, {source})"
            size = None
            if current.get("value") is not None and target.get("value") is not None:
                size = atlas.gap_size(definition, current["value"], target["value"])
            room = None
            if target.get("value") is not None and limit.get("value") is not None:
                room = atlas.headroom(definition, target["value"], limit["value"])
            room_text = "–" if room is None else ("beyond the limit" if room < 0 else atlas.format_gap(definition, room).replace("met", "at the limit"))
            lines.append(
                f"| {name} | {current_text} | {atlas.format_value(target.get('value'), unit)} "
                f"| {atlas.format_value(limit.get('value'), unit)} | {atlas.format_gap(definition, size)} | {room_text} |"
            )
            details = []
            if metric.get("conditions"):
                details.append(f"measured as: {cell(metric['conditions'])}")
            if current.get("note"):
                details.append(f"current: {cell(current['note'])}")
            if target.get("rationale"):
                source = f" ({evidence_link(page, target['evidence'])})" if target.get("evidence") else ""
                details.append(f"target: {cell(target['rationale'])}{source}")
            if limit.get("basis"):
                source = f" ({evidence_link(page, limit['evidence'])})" if limit.get("evidence") else ""
                details.append(f"limit: {cell(limit['basis'])}{source}")
            if details:
                notes.append(f"- **{cell(definition.get('name', metric.get('metric', '')))}**: " + "; ".join(details) + ".")
        lines += ["", *notes, ""] if notes else [""]

    requires = tech.requires()
    required_by = ctx.required_by.get(tech.id, [])
    if requires or required_by:
        lines += ["## Dependencies", ""]
        ids = [tech.id] + [r.get("technology") for r in requires] + [t.id for t, _ in required_by]
        edges = [(tech.id, r.get("technology")) for r in requires] + [(t.id, tech.id) for t, _ in required_by]
        lines += mermaid(ctx, list(dict.fromkeys(ids)), edges, focus=tech.id)
        lines.append("")
    if requires:
        lines += ["### Depends on", "", "| Technology | Atlas status | Why | What it must deliver |", "|---|---|---|---|"]
        for requirement in requires:
            dep = ctx.techs.get(requirement.get("technology", ""))
            if dep is None:
                continue
            need = need_text(ctx, requirement)
            lines.append(f"| {link(page, dep.page, dep.name)} | {dep.status} | {cell(requirement.get('why', ''))} | {need} |")
        lines.append("")
    if required_by:
        lines += ["### Required by", "", "| Technology | Why | What it needs from this one |", "|---|---|---|"]
        for dependent, requirement in sorted(required_by, key=lambda item: item[0].id):
            lines.append(
                f"| {link(page, dependent.page, dependent.name)} | {cell(requirement.get('why', ''))} | {need_text(ctx, requirement)} |"
            )
        lines.append("")

    gaps = sorted(tech.gaps(), key=lambda gap: (SEVERITY_ORDER.get(gap.get("severity"), 9), gap.get("title", "")))
    if gaps:
        lines += ["## Gaps", ""]
        by_id = {metric.get("id"): metric for metric in metrics}
        for gap in gaps:
            lines += [f"### {cell(gap.get('title', gap.get('id', '')))}", ""]
            facts = [
                f"severity **{gap.get('severity', '')}**",
                f"status **{gap.get('status', '')}**",
                f"type {gap.get('type', '')}",
                f"layer {gap.get('layer', '')}",
            ]
            if gap.get("metric") in by_id:
                facts.append(f"blocks {cell(ctx.metric_def(by_id[gap['metric']]).get('name', gap['metric']))}")
            lines += ["; ".join(facts) + ".", ""]
            if gap.get("description"):
                lines += [" ".join(gap["description"].split()), ""]
            blocked = gap.get("blocked_by", [])
            if blocked:
                names = ", ".join(
                    f"{link(page, ctx.techs[b].page, ctx.techs[b].name)} ({ctx.techs[b].status})" for b in blocked if b in ctx.techs
                )
                lines += [f"Blocked by: {names}.", ""]
            approaches = gap.get("approach", [])
            if approaches:
                lines += ["| Approach | Readiness | Evidence |", "|---|---|---|"]
                scale = ctx.tax.scale_of(tech)
                for approach in approaches:
                    cards = ", ".join(evidence_link(page, key) for key in approach.get("evidence", [])) or "–"
                    lines.append(
                        f"| {cell(approach.get('name', ''))} | {ctx.tax.level_name(scale, approach.get('readiness'))} | {cards} |"
                    )
                lines.append("")
            if gap.get("evidence"):
                lines += ["Evidence: " + ", ".join(evidence_link(page, key) for key in gap["evidence"]) + ".", ""]

    keys = ctx.cited_keys(tech)
    if keys:
        lines += ["## Evidence", "", "| Card | Source | Class | Checked |", "|---|---|---|---|"]
        for key in keys:
            if key not in ctx.cards:
                continue
            _, card = ctx.cards[key]
            lines.append(f"| {evidence_link(page, key)} | {source_text(card)} | {card.get('class', '')} | {card.get('status', '')} |")
        lines.append("")

    terms = data.get("search_terms", [])
    if terms:
        lines += ["## Search terms", "", "Where the `scout-literature` skill starts: " + "; ".join(f"`{t}`" for t in terms) + ".", ""]
    return "\n".join(lines).rstrip() + "\n"


def need_text(ctx: Context, requirement: dict) -> str:
    parts = []
    if requirement.get("metric"):
        definition = ctx.tax.metrics.get(requirement["metric"], {})
        value = requirement.get("value")
        text = cell(definition.get("name", requirement["metric"]))
        if value is not None:
            text += f": {atlas.format_value(value, definition.get('unit', ''))}"
        parts.append(text)
    if requirement.get("need"):
        parts.append(cell(requirement["need"]))
    return "; ".join(parts) or "–"


def source_text(card: dict) -> str:
    authors = card.get("authors", [])
    first = authors[0].split(",")[0] if authors else "?"
    who = f"{first} et al." if len(authors) > 1 else first
    where = cell(card.get("venue", "")) or card.get("type", "")
    if card.get("doi"):
        target = f"https://doi.org/{card['doi']}"
    elif card.get("arxiv"):
        target = f"https://arxiv.org/abs/{card['arxiv']}"
    elif card.get("pmid"):
        target = f"https://pubmed.ncbi.nlm.nih.gov/{card['pmid']}/"
    elif card.get("nct"):
        target = f"https://clinicaltrials.gov/study/{card['nct']}"
    else:
        target = card.get("url", "")
    title = cell(card.get("title", ""))
    return f"{cell(who)} ({card.get('year', '')}), [{title}]({target}), {where}"


def domain_page(ctx: Context, domain_id: str) -> str:
    domain = ctx.tax.domains[domain_id]
    page = f"atlas/{domain_id}/README.md"
    techs = [t for t in ctx.techs.values() if t.domain == domain_id]
    scale = ctx.tax.scales.get(domain.get("readiness_scale"), {})
    lines = [
        f"# {domain['name']}",
        "",
        HEADER.format(source="taxonomy/domains.toml and atlas/" + domain_id),
        "",
        domain.get("summary", ""),
        "",
        f"Readiness scale: {scale.get('name', domain.get('readiness_scale'))}, unless a technology states another.",
        "",
        f"Moderators: {people(page, domain.get('moderators', []), 'moderators')}.",
        "",
    ]
    if domain_id == "health" or domain_id == "neurotech":
        lines += [
            "> This page maps research, not treatment. Nothing in the atlas is medical advice.",
            "",
        ]
    if not techs:
        lines += ["No technologies yet. " + link(page, "CONTRIBUTING.md", "Propose one") + ".", ""]
        return "\n".join(lines).rstrip() + "\n"
    lines += [
        "| Technology | Atlas status | Readiness | Headline metric | Current | Target | Gap to target |",
        "|---|---|---|---|---|---|---|",
    ]
    for tech in sorted(techs, key=lambda t: (STATUS_ORDER.index(t.status) if t.status in STATUS_ORDER else 9, t.name)):
        lines.append(
            f"| [{cell(tech.name)}]({tech.slug}.md) | {tech.status} | {ctx.readiness(tech)} | "
            + " | ".join(ctx.headline_cells(tech, page))
            + " |"
        )
    outside = sorted(
        {r.get("technology") for t in techs for r in t.requires() if not r.get("technology", "").startswith(domain_id + "/")}
    )
    if outside:
        lines += ["", "Depends on technologies in other domains: " + ", ".join(
            link(page, ctx.techs[o].page, ctx.techs[o].name) for o in outside if o in ctx.techs
        ) + "."]
    return "\n".join(lines).rstrip() + "\n"


def status_page(ctx: Context) -> str:
    page = "STATUS.md"
    techs = list(ctx.techs.values())
    by_status = defaultdict(int)
    for tech in techs:
        by_status[tech.status] += 1
    gaps = [(tech, gap) for tech in techs for gap in tech.gaps()]
    open_gaps = [(t, g) for t, g in gaps if g.get("status") != "closed"]
    card_status = defaultdict(int)
    for _, card in ctx.cards.values():
        card_status[card.get("status", "")] += 1
    summary_status = ", ".join(f"{by_status[s]} {s}" for s in STATUS_ORDER if by_status[s])
    summary_cards = ", ".join(f"{card_status[s]} {s}" for s in ("verified", "machine-checked", "unverified", "rejected") if card_status[s])
    lines = [
        "# Status of the atlas",
        "",
        HEADER.format(source="atlas/, evidence/ and taxonomy/"),
        "",
        "Where every technology stands, what blocks it, and the evidence behind each number. The atlas",
        "status says how much of a technology is mapped; readiness says how mature the technology is.",
        "",
        f"**{len(techs)} technologies** in {len(ctx.tax.domains)} domains ({summary_status}). "
        f"**{len(open_gaps)} open gaps**, {sum(1 for _, g in open_gaps if g.get('severity') == 'critical')} of them critical. "
        f"**{len(ctx.cards)} evidence cards** ({summary_cards or 'none yet'}).",
        "",
        "## Domains",
        "",
        "| Domain | Technologies | Mapped or tracked | Open gaps | Critical |",
        "|---|---|---|---|---|",
    ]
    for domain_id, domain in ctx.tax.domains.items():
        in_domain = [t for t in techs if t.domain == domain_id]
        mapped = sum(1 for t in in_domain if t.status in ("mapped", "tracked", "achieved"))
        domain_gaps = [g for t, g in open_gaps if t.domain == domain_id]
        critical = sum(1 for g in domain_gaps if g.get("severity") == "critical")
        lines.append(
            f"| [{cell(domain['name'])}](atlas/{domain_id}/README.md) | {len(in_domain)} | {mapped} | {len(domain_gaps)} | {critical} |"
        )
    lines += [
        "",
        "## Headline metrics",
        "",
        "One number per technology, the one that best says how far it has to go.",
        "",
        "| Technology | Domain | Atlas status | Readiness | Headline metric | Current | Target | Gap to target |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for tech in sorted(techs, key=lambda t: (t.domain, t.name)):
        if tech.headline() is None:
            continue
        lines.append(
            f"| {link(page, tech.page, tech.name)} | {tech.domain} | {tech.status} | {ctx.readiness(tech)} | "
            + " | ".join(ctx.headline_cells(tech, page))
            + " |"
        )
    depended = sorted(ctx.required_by.items(), key=lambda item: (-len(item[1]), item[0]))
    depended = [(tech_id, users) for tech_id, users in depended if tech_id in ctx.techs and len(users) >= 1]
    if depended:
        lines += [
            "",
            "## Most depended on",
            "",
            "A breakthrough here moves every technology that requires it.",
            "",
            "| Technology | Required by | Domains reached | Atlas status |",
            "|---|---|---|---|",
        ]
        for tech_id, users in depended[:15]:
            tech = ctx.techs[tech_id]
            domains = sorted({user.domain for user, _ in users})
            lines.append(f"| {link(page, tech.page, tech.name)} | {len(users)} | {', '.join(domains)} | {tech.status} |")
    critical = sorted(
        [(t, g) for t, g in open_gaps if g.get("severity") == "critical"], key=lambda item: (item[0].domain, item[0].name)
    )
    if critical:
        lines += [
            "",
            "## Critical gaps",
            "",
            "| Gap | Technology | Type | Status | Blocked by |",
            "|---|---|---|---|---|",
        ]
        for tech, gap in critical:
            blocked = ", ".join(link(page, ctx.techs[b].page, ctx.techs[b].name) for b in gap.get("blocked_by", []) if b in ctx.techs)
            lines.append(
                f"| {cell(gap.get('title', ''))} | {link(page, tech.page, tech.name)} | {gap.get('type', '')} "
                f"| {gap.get('status', '')} | {blocked or '–'} |"
            )
    edges = [(tech.id, r.get("technology")) for tech in techs for r in tech.requires() if r.get("technology") in ctx.techs]
    if edges:
        ids = list(dict.fromkeys([e[0] for e in edges] + [e[1] for e in edges]))
        lines += ["", "## Dependency graph", "", "An arrow points from a technology to one it depends on.", ""]
        lines += mermaid(ctx, ids, edges)
    return "\n".join(lines).rstrip() + "\n"


def evidence_page(ctx: Context) -> str:
    page = "evidence/README.md"
    lines = [
        "# Evidence",
        "",
        HEADER.format(source="evidence/*.toml"),
        "",
        "One card per source. A card records what the source measured, under which conditions, with a",
        "short verbatim quote. See [decision 0006](../docs/decisions/0006-evidence-policy.md).",
        "",
    ]
    if not ctx.cards:
        return "\n".join(lines + ["No cards yet."]).rstrip() + "\n"
    lines += ["| Card | Source | Type | Class | Checked | Cited by |", "|---|---|---|---|---|---|"]
    for key, (_, card) in sorted(ctx.cards.items()):
        cited = ", ".join(link(page, ctx.techs[t].page, ctx.techs[t].name) for t in sorted(ctx.cited_by.get(key, [])) if t in ctx.techs)
        lines.append(
            f"| [{key}]({key}.toml) | {source_text(card)} | {card.get('type', '')} | {card.get('class', '')} "
            f"| {card.get('status', '')} | {cited or '–'} |"
        )
    return "\n".join(lines).rstrip() + "\n"


def outputs() -> dict[str, str]:
    ctx = Context()
    files = {"STATUS.md": status_page(ctx), "evidence/README.md": evidence_page(ctx)}
    for domain_id in ctx.tax.domains:
        files[f"atlas/{domain_id}/README.md"] = domain_page(ctx, domain_id)
    for tech in ctx.techs.values():
        files[tech.page] = technology_page(ctx, tech)
    return files


def stale_pages(files: dict[str, str]) -> list[str]:
    """Generated technology pages whose TOML file no longer exists."""
    stale = []
    for path in sorted((atlas.ROOT / "atlas").glob("*/*.md")):
        relative = path.relative_to(atlas.ROOT).as_posix()
        if path.name != "README.md" and relative not in files:
            stale.append(relative)
    return stale


def main(argv: list[str]) -> int:
    check = "--check" in argv
    files = outputs()
    if atlas.LOAD_ERRORS:
        for relative, message in atlas.LOAD_ERRORS.items():
            print(f"error: {relative}: {message}", file=sys.stderr)
        return 1
    out_of_date = []
    for relative, content in files.items():
        path = atlas.ROOT / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            out_of_date.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {relative}")
    for relative in stale_pages(files):
        if check:
            out_of_date.append(relative)
        else:
            (atlas.ROOT / relative).unlink()
            print(f"removed {relative}")
    for relative in out_of_date:
        print(f"error: {relative} is out of date; run python3 tools/generate.py", file=sys.stderr)
    return 1 if out_of_date else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
